server:
  port: 9091
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:user-service-db
  h2:
    console:
      enabled: true
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
eureka:
  client:
    register-with-eureka: true