spring:
  application:
    name: config-service
  config:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HamzaOuggadi/FraudDetection
eureka:
  client:
    register-with-eureka: true
